stages:
  - deploy

default:
  image: node:20-bullseye

variables:
  # Set the Hugo version you want to use.
  HUGO_VERSION: "0.143.1"

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - apt-get update && apt-get install -y wget tar
    - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
    - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
    - hugo --minify
    - npm install --global vercel
    - vercel deploy public --token=$VERCEL_TOKEN
  artifacts:
    paths:
      - public

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - apt-get update && apt-get install -y wget tar
    - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
    - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
    - hugo --minify
    - npm install --global vercel
    - vercel deploy public --prod --token=$VERCEL_TOKEN
  artifacts:
    paths:
      - public
