baseURL = "http://blog.gregtech.eu"
title = "GregTech"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = ""

[markup.highlight]
style = "github-dark"

[params]
  author = "Gregor Podjed"
  info = ["Web Developer", "FOSS Enthusiast", "Sysadmin", "Linux Nerd"]
  description = "My personal website"
  keywords = "blog,developer,personal,webdev,linux,minecraft,tech,privacy,anonymity,dev"
  avatarurl = "/static/kitty.webp"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/static/kitty.webp"
  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/gragorther"
[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 3
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"

#[[params.social]]
#  name = "Twitter"
#  icon = "fa-brands fa-x-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
name = "Contact me"
weight = "3"
url = "contact/"
